# Generated by Django 3.1.7 on 2021-04-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('previous_close', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
