# Generated by Django 3.1.7 on 2021-04-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justmodels', '0002_stks_stocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='previous_close',
            new_name='prev close',
        ),
    ]
