# Generated by Django 3.1.7 on 2021-04-06 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justmodels', '0006_auto_20210406_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='companyName',
        ),
    ]
